-- Collaboration schema for iTECify (no Docker stage)
-- Compatible with your existing unquoted SQL naming style.

CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    createdby BIGINT REFERENCES users(id) ON DELETE SET NULL,
    createdat TIMESTAMPTZ DEFAULT NOW(),
    updatedat TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roommembers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roomid BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    userid BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'member' CHECK (role IN ('owner', 'member', 'viewer', 'ai-agent')),
    joinedat TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (roomid, userid)
);

CREATE TABLE IF NOT EXISTS roomfiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roomid BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    path TEXT NOT NULL,
    language TEXT DEFAULT 'plaintext',
    content TEXT DEFAULT '',
    updatedby BIGINT REFERENCES users(id) ON DELETE SET NULL,
    createdat TIMESTAMPTZ DEFAULT NOW(),
    updatedat TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (roomid, path)
);

CREATE TABLE IF NOT EXISTS editsnapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roomid BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    fileid BIGINT NOT NULL REFERENCES roomfiles(id) ON DELETE CASCADE,
    userid BIGINT REFERENCES users(id) ON DELETE SET NULL,
    source TEXT DEFAULT 'manual-save',
    language TEXT DEFAULT 'plaintext',
    content TEXT DEFAULT '',
    createdat TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_roommembers_roomid ON roommembers(roomid);
CREATE INDEX IF NOT EXISTS idx_roommembers_userid ON roommembers(userid);
CREATE INDEX IF NOT EXISTS idx_roomfiles_roomid ON roomfiles(roomid);
CREATE INDEX IF NOT EXISTS idx_roomfiles_updatedat ON roomfiles(updatedat);
CREATE INDEX IF NOT EXISTS idx_editsnapshots_room_file_created ON editsnapshots(roomid, fileid, createdat DESC);

-- Optional seed room + file for quick testing:
-- INSERT INTO rooms (name, createdby) VALUES ('Demo Room', 1);
-- INSERT INTO roomfiles (roomid, path, language, content, updatedby)
-- VALUES (1, 'main.js', 'javascript', 'console.log("hello from room");', 1);
